### ISSUE TITLE
为什么不用payload-dumper-go 呢

### ISSUE THREAD

**Issue by httpsColon** [tosasitill/MagiskPatchAction#1]

**Comment by httpsColon** [comment]
magisk patch的action 还没写吧，用的哪个项目啊，https://github.com/jax0ncai/Magisk_patche.git这个可以么

**Comment by tosasitill** [comment]
1、还没写 因为我没手机测试这样修补是否成功可行
2、payload-dumper-go只是可以解压payload，而并非所有 ROM 都是 payload 格式，为了更好的兼容性，用的是这位大佬的 [项目](https://github.com/ShivamKumarJha/Firmware_extractor) 进行微小改动

**Comment by tosasitill** [comment]
更换为 payload dumper go
